### ISSUE TITLE
Support multiple WeDos

### ISSUE THREAD

**Issue by cpseager** [tarling/blockly-wedo#1]
Blocks need A-Z identifier.

**Comment by tarling** [comment]
> So, for instance, in blocks motors are always followed by a letter A -Z in a drop down.
> 
> So
> 
> turn motor/lights A/B/C...Z on
> turn motor/lights A/B/C...Z off
> 
> sensors are the same A-Z (no tilt/distance blocks are needed at all, just sensorA...sensorZ). 
> That way there is no confusion if you use two tilt sensors (e.g. as a joystick in each hand)

**Comment by tarling** [comment]
> turn motor/lights A/B/C...Z on

Should we allow selection of motor/light - isn't it similar to "sensor A", in that we are just directing a value towards an output?

But

> turn output A/B/C...Z on

isn't so nice. 

I could put a drop down there for motor/lights, but ignore its value. What do you think?

**Comment by cpseager** [comment]
I think we should still leave motor/lights there (and still use them - if it is not the correct thing connected to that port the block is ignored - that code is already there).

https://github.com/tarling/blockly-wedo/blob/1cfaebb3859a31cf00e648642af34724f7647b08/app/js/devices/wedo/wedo-usb.js#L241

**Comment by cpseager** [comment]
I suppose a separate

turn everything off

block may also be useful?

**Comment by cpseager** [comment]
How do you feel about that motor look?

I was just wondering if listing them in one (long!) drop down list as motorA - motorZ lightsA - lightZ would look prettier than the two lists side by side?

**Comment by cpseager** [comment]
or even two separate blocks in the menu?

turn motor [A] on
turn lights [A] on

**Comment by cpseager** [comment]
or dump motor/lighst after all and just say

turn [A] on
turn [B] off
set power of [C] to 100

**Comment by tarling** [comment]
I didn't mind the two menus motor/lights and a/b/c..., but think that the simpler version is better. Didn't like the idea of a combined list of motor a/motor b/../light a/light b

**Comment by cpseager** [comment]
agree, but you will need to combine the isLight and isMotor etc. at the code link above (as same block applies to both now)
