### ISSUE TITLE
tilt sensor up/down/left/right

### ISSUE THREAD

**Issue by cpseager** [tarling/blockly-wedo#8]
Scratch deliberately avoids this (using numbers instead) as the sensor can be held wire towards you, wire away from you, upside down...

**Comment by tarling** [comment]
How does the user know what a valid input value is? By having a drop down, they are at least limited to the set of correct values. A drop down with numbers might be confusing. What would be a better solution?

**Comment by cpseager** [comment]
Many kids don't know left from right, and it will reverse anyway if they build the sensor into a lego model upside down, back to front etc. Have a look at these ideas, the sensors are not always the same way around:

https://education.lego.com/en-gb/lesi/support/product-support/wedo/wedo-base-set-9580/building-instructions

So generally they will just experiment i.e move the model and watch the number change on the left hand side of the screen to work out what they want (as with distance). So nothing special is needed for tilt, they can just say

wait until sensorA = 2

if sensorB not = 0 ...

etc. etc.

**Comment by tarling** [comment]
OK. Shall we remove all decimal places from all number inputs? Are there any situations in any blocks where a decimal is valid? Or negative values?

**Comment by cpseager** [comment]
wait 1.5 seconds would be valid e.g. for switching a motor on.

**Comment by cpseager** [comment]
Looking again at the official lego software they do actually do this (but Scratch doesn't) i.e. they do have a tilt input but avoid the left/right issue with the following wording, so if you did like it maybe it is worth having it as a tilt input type using this wording instead

this way (==2)
that way (==4)
up (==3)
down (==1)
no tilt (== 0)
any tilt (!=0)

**Comment by cpseager** [comment]
Please see 2a6bdae

Although a few extra blocks I think this makes it much clearer for students how to use both distance and tilt sensors - effectively a block for each.
